### ISSUE TITLE
hubot-lark内置指令无法使用

### ISSUE THREAD

**Issue by ptrjeffrey** [hlxwell/hubot-lark#12]
发送ping应该回一个pong
但是没反应

**Comment by ptrjeffrey** [comment]
已经把help和ping这些基本内置命令重写了...

**Comment by hlxwell** [comment]
能做一个 pull request 吗

**Comment by ptrjeffrey** [comment]
发了外部的方式，不是从内部直接支持的。并且后面要添加说明都需要去那个里面添加，而不是原来的方式了。
